include:
  - project: 'smartive/ci-templates'
    ref: v1.1.1
    file: '/all-templates.yml'

image: mcr.microsoft.com/dotnet/core/sdk:3.0

stages:
  - test
  - release
  - deploy

# Testing

test:
  stage: test
  extends: .base
  script:
    - ./build.sh --target Test
  except:
    - tags

# Release

create release:
  extends: .create-manual-release
  stage: release
  only:
    - master

# Deploy to nuget

publish:
  extends: .base
  stage: deploy
  dependencies: []
  script:
    - ./build.sh --target Publish
  artifacts:
    paths:
      - artifacts/
  only:
    - tags
