include:
  - 'https://gitlab.com/smartive/open-source/gitlab-ci-templates/raw/master/templates.yml'

image: microsoft/dotnet:2.2-sdk

stages:
  - test
  - release
  - deploy

# Testing

test:
  stage: test
  extends: .base
  script:
    - ./build.sh --target CoverageReport
  coverage: '/\s*Line coverage:\s([\d\.]+)%/'
  artifacts:
    paths:
      - coverage/
  except:
    - tags

# Release

create release:
  extends: .create-release
  stage: release
  dependencies: []
  when: manual
  only:
    - master

# Deploy to nuget

publish:
  extends: .base
  stage: deploy
  dependencies: []
  script:
    - ./build.sh --target=Publish
  artifacts:
    paths:
      - artifacts/
  only:
    - tags
