image: microsoft/dotnet:2.1-sdk

stages:
  - test
  - deploy

# Templates

.test:
  stage: test
  script:
    - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CopyLocalLockFileAssemblies=true $PACKAGE.Test
  coverage: /$PACKAGE\s*\|\s*([\d\.]+)/
  except:
    - tags

.nuget:
  stage: deploy
  script:
    - dotnet pack -o ../nuget -c Release /p:PackageVersion=$(echo $CI_COMMIT_TAG | cut -c 2-) $PACKAGE
    - dotnet nuget push ./nuget/$PACKAGE.$(echo $CI_COMMIT_TAG | cut -c 2-).nupkg --api-key $NUGET_KEY --source https://www.nuget.org/api/v2/package
  only:
    - tags

# Testing

lint:
  stage: test
  script:
    - dotnet build Smartive.Core -c Release
  except:
    - tags

test database:
  extends: .test
  variables:
    PACKAGE: Smartive.Core.Database

test debug:
  extends: .test
  variables:
    PACKAGE: Smartive.Core.Debug

# Release

create release:
  stage: deploy
  image: node:10
  before_script:
    - npm ci
  script:
    - npx semantic-release
  only:
    - master

# Deploy to nuget

publish composition:
  extends: .nuget
  variables:
    PACKAGE: Smartive.Core

publish database:
  extends: .nuget
  variables:
    PACKAGE: Smartive.Core.Database

publish debug:
  extends: .nuget
  variables:
    PACKAGE: Smartive.Core.Debug
