image: microsoft/dotnet:2.1-sdk

stages:
  - test
  - build
  - deploy

test database:
  stage: test
  script:
    - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov Smartive.Core.Database.Test
  coverage: /Smartive.Core.Database\s*\|\s*([\d\.]+)/
  except:
    - tags

style cop database:
  stage: test
  script:
    - dotnet build Smartive.Core.Database
  except:
    - tags

build database:
  stage: build
  script:
    - dotnet build Smartive.Core.Database -c Release
  except:
    - tags

create release:
  stage: deploy
  image: node:10-alpine
  before_script:
    - npm ci
  script:
    - npx semantic-release
  only:
    - master

publish database:
  stage: deploy
  script:
    - dotnet pack -o ../nuget -c Release /p:PackageVersion=$CI_COMMIT_TAG Smartive.Core.Database
    - dotnet nuget push ./nuget/*.nupkg --api-key $NUGET_KEY
  only:
    - tags
