include:
  - 'https://gitlab.com/smartive/open-source/gitlab-ci-templates/raw/master/templates.yml'

image: microsoft/dotnet:2.1-sdk

stages:
  - test
  - release
  - deploy

# Testing

test:
  stage: test
  extends: .base
  script:
    - ./build.sh --target=Coverage
  artifacts:
    paths:
      - coverage/
  except:
    - tags

# Release

create release:
  extends: .create-release
  stage: release
  only:
    - master

# Deploy to nuget

publish:
  extends: .base
  script:
    - ./build.sh --target=Publish
  only:
    - tags
