name: .Net Release

on: [workflow_dispatch]

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/exec
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
